[2022-12-03 01:38:14,511] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.call_dataset_task manual__2022-12-03T01:36:08.312041+00:00 [queued]>
[2022-12-03 01:38:14,525] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.call_dataset_task manual__2022-12-03T01:36:08.312041+00:00 [queued]>
[2022-12-03 01:38:14,525] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-03 01:38:14,525] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-03 01:38:14,525] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-03 01:38:14,541] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): call_dataset_task> on 2022-12-03 01:36:08.312041+00:00
[2022-12-03 01:38:14,549] {standard_task_runner.py:52} INFO - Started process 308 to run task
[2022-12-03 01:38:14,556] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'call_dataset_task', 'manual__2022-12-03T01:36:08.312041+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp4hnwffu1', '--error-file', '/tmp/tmp7d2_hrq4']
[2022-12-03 01:38:14,557] {standard_task_runner.py:77} INFO - Job 31: Subtask call_dataset_task
[2022-12-03 01:38:14,635] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.call_dataset_task manual__2022-12-03T01:36:08.312041+00:00 [running]> on host c87e816ea86f
[2022-12-03 01:38:14,713] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=call_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-03T01:36:08.312041+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-03T01:36:08.312041+00:00
[2022-12-03 01:38:14,715] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-03 01:38:14,716] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://datausa.io/api/data?drilldowns=Nation&measures=Population/data_usa.json > /opt/***/data_usa.json']
[2022-12-03 01:38:14,735] {subprocess.py:85} INFO - Output:
[2022-12-03 01:38:15,772] {subprocess.py:89} INFO - {"error":"Query must contain at least one measure."}
[2022-12-03 01:38:15,773] {subprocess.py:93} INFO - Command exited with return code 0
[2022-12-03 01:38:15,837] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=call_dataset_task, execution_date=20221203T013608, start_date=20221203T013814, end_date=20221203T013815
[2022-12-03 01:38:15,901] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-03 01:38:15,997] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
