[2022-12-02 23:50:07,130] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.call_dataset_task manual__2022-12-02T23:11:56.929669+00:00 [queued]>
[2022-12-02 23:50:07,150] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.call_dataset_task manual__2022-12-02T23:11:56.929669+00:00 [queued]>
[2022-12-02 23:50:07,158] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-02 23:50:07,159] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-02 23:50:07,159] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-02 23:50:07,182] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): call_dataset_task> on 2022-12-02 23:11:56.929669+00:00
[2022-12-02 23:50:07,191] {standard_task_runner.py:52} INFO - Started process 69 to run task
[2022-12-02 23:50:07,212] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'call_dataset_task', 'manual__2022-12-02T23:11:56.929669+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpnzgxcf53', '--error-file', '/tmp/tmpk98lcb_f']
[2022-12-02 23:50:07,214] {standard_task_runner.py:77} INFO - Job 14: Subtask call_dataset_task
[2022-12-02 23:50:07,397] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.call_dataset_task manual__2022-12-02T23:11:56.929669+00:00 [running]> on host c87e816ea86f
[2022-12-02 23:50:07,628] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=call_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-02T23:11:56.929669+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-02T23:11:56.929669+00:00
[2022-12-02 23:50:07,632] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-02 23:50:07,635] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://datausa.io/api/data?drilldowns=Nation&measures=Population/data_usa.json > /opt/***/data_usa.json']
[2022-12-02 23:50:07,696] {subprocess.py:85} INFO - Output:
[2022-12-02 23:50:09,004] {subprocess.py:89} INFO - {"error":"Query must contain at least one measure."}
[2022-12-02 23:50:09,005] {subprocess.py:93} INFO - Command exited with return code 0
[2022-12-02 23:50:09,118] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=call_dataset_task, execution_date=20221202T231156, start_date=20221202T235007, end_date=20221202T235009
[2022-12-02 23:50:09,201] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-02 23:50:09,289] {dagrun.py:628} WARNING - Failed to get task '<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2022-12-02T23:11:56.929669+00:00 [removed]>' for dag 'data_ingestion_gcs_dag'. Marking it as removed.
[2022-12-02 23:50:09,324] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
