[2022-12-03 01:27:18,756] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.call_dataset_task manual__2022-12-03T01:26:30.239540+00:00 [queued]>
[2022-12-03 01:27:18,786] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.call_dataset_task manual__2022-12-03T01:26:30.239540+00:00 [queued]>
[2022-12-03 01:27:18,786] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-03 01:27:18,786] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-03 01:27:18,787] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-03 01:27:18,838] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): call_dataset_task> on 2022-12-03 01:26:30.239540+00:00
[2022-12-03 01:27:18,864] {standard_task_runner.py:52} INFO - Started process 207 to run task
[2022-12-03 01:27:18,874] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'call_dataset_task', 'manual__2022-12-03T01:26:30.239540+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpnur9qipn', '--error-file', '/tmp/tmpsqaem8wz']
[2022-12-03 01:27:18,884] {standard_task_runner.py:77} INFO - Job 20: Subtask call_dataset_task
[2022-12-03 01:27:19,063] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.call_dataset_task manual__2022-12-03T01:26:30.239540+00:00 [running]> on host c87e816ea86f
[2022-12-03 01:27:19,226] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=call_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-03T01:26:30.239540+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-03T01:26:30.239540+00:00
[2022-12-03 01:27:19,228] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-03 01:27:19,229] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://datausa.io/api/data?drilldowns=Nation&measures=Population/data_usa.json > /opt/***/data_usa.json']
[2022-12-03 01:27:19,256] {subprocess.py:85} INFO - Output:
[2022-12-03 01:27:19,834] {subprocess.py:89} INFO - {"error":"Query must contain at least one measure."}
[2022-12-03 01:27:19,835] {subprocess.py:93} INFO - Command exited with return code 0
[2022-12-03 01:27:19,934] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=call_dataset_task, execution_date=20221203T012630, start_date=20221203T012718, end_date=20221203T012719
[2022-12-03 01:27:20,031] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-03 01:27:20,162] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
