[2022-12-03 01:44:32,997] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.call_dataset_task manual__2022-12-03T01:44:31.327998+00:00 [queued]>
[2022-12-03 01:44:33,011] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.call_dataset_task manual__2022-12-03T01:44:31.327998+00:00 [queued]>
[2022-12-03 01:44:33,012] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-03 01:44:33,012] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-03 01:44:33,012] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-03 01:44:33,027] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): call_dataset_task> on 2022-12-03 01:44:31.327998+00:00
[2022-12-03 01:44:33,035] {standard_task_runner.py:52} INFO - Started process 103 to run task
[2022-12-03 01:44:33,041] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'call_dataset_task', 'manual__2022-12-03T01:44:31.327998+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpz9ab7v97', '--error-file', '/tmp/tmp8ut9ays5']
[2022-12-03 01:44:33,043] {standard_task_runner.py:77} INFO - Job 36: Subtask call_dataset_task
[2022-12-03 01:44:33,129] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.call_dataset_task manual__2022-12-03T01:44:31.327998+00:00 [running]> on host c87e816ea86f
[2022-12-03 01:44:33,233] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=call_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-03T01:44:31.327998+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-03T01:44:31.327998+00:00
[2022-12-03 01:44:33,235] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-03 01:44:33,236] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://datausa.io/api/data?drilldowns=Nation&measures=Population/data_usa.json > /opt/***/data_usa.json']
[2022-12-03 01:44:33,256] {subprocess.py:85} INFO - Output:
[2022-12-03 01:44:33,508] {subprocess.py:89} INFO - {"error":"Query must contain at least one measure."}
[2022-12-03 01:44:33,509] {subprocess.py:93} INFO - Command exited with return code 0
[2022-12-03 01:44:33,552] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=call_dataset_task, execution_date=20221203T014431, start_date=20221203T014432, end_date=20221203T014433
[2022-12-03 01:44:33,589] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-03 01:44:33,643] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
